const frases_motivadoras = [
  "Você já sobreviveu a 100% dos seus dias difíceis até agora. Isso prova que você é mais forte do que imagina.", 
  "A tempestade não dura para sempre. Respire e espere o sol voltar.", 
  "Sua dor é válida, mas sua capacidade de superá-la é ainda maior.", 
  "Não desista de si mesmo. Ainda há capítulos lindos por vir na sua história.", 
  "Você não está sozinho(a). Mesmo no silêncio, há pessoas que se importam.", 
  "A cura não é linear, mas cada pequeno passo conta.", 
  "Você não é um fardo. Sua existência já faz diferença no mundo.", 
  "A noite mais escura produz as estrelas mais brilhantes.", 
  "Permita-se sentir, mas não deixe que a dor defina quem você é.", 
  "Você não precisa ser perfeito(a), só precisa ser você mesmo(a).", 
  "Essa ansiedade é um sinal de que você se importa, não de que está falhando.", 
  "Respire fundo. Você não está em perigo, só está desconfortável.", 
  "Uma coisa de cada vez. Você não precisa resolver tudo agora.", 
  "Os pensamentos são como nuvens: eles passam. Você não é seus medos.", 
  "Preocupação não evita o sofrimento, só rouba sua paz no presente.", 
  "Você já enfrentou a ansiedade antes e venceu. Vai conseguir de novo.", 
  "Pare. Olhe em volta. Você está seguro(a) neste momento.", 
  "Acalme seu coração: nada dura para sempre, nem mesmo a ansiedade.", 
  "Você é maior do que esse turbilhão de pensamentos.", 
  "Ansiedade não é sua inimiga, é uma parte de você que precisa de cuidado.", 
  "Hoje foi difícil, e tudo bem. Amanhã é uma nova chance.", 
  "Você não está fraco(a) por sentir isso. Está humano(a).", 
  "Até a menor luz vence a escuridão. Segure-se a ela.", 
  "Não force a felicidade. Às vezes, 'estar em paz' já é o suficiente.", 
  "Sua mente pode mentir para você. Acredite nos que veem sua força.", 
  "Você não está preso(a) nessa dor para sempre.", 
  "Mesmo que não veja sentido agora, sua vida importa.", 
  "Descanse, mas não desista. Você merece ver dias melhores.", 
  "A depressão não é preguiça, é uma batalha invisível.", 
  "Você não está quebrado(a), só está se reconstruindo.", 
  "Trate-se com a mesma bondade que ofereceria a um amigo querido.", 
  "Você merece paciência, especialmente de você mesmo(a).", 
  "Erros não te definem. Eles só provam que você está tentando.", 
  "Não compare sua jornada com a de ninguém. Cada um cura no seu tempo.", 
  "Você não precisa justificar seu cansaço. Descansar também é produtivo.", 
  "Permita-se recomeçar quantas vezes forem necessárias.", 
  "Você é suficiente, mesmo nos dias em que não produz nada.", 
  "Não se culpe por recair. A cura tem altos e baixos.", 
  "Seu valor não depende da sua produtividade.", 
  "Você é amado(a), mesmo quando não consegue amar a si mesmo(a).",
  "Pedir ajuda não é fraqueza, é um ato de coragem.", 
  "Você não precisa carregar esse peso sozinho(a). Deixe outros te ajudarem.", 
  "Terapia não é para 'loucos', é para pessoas que querem se entender melhor.", 
  "Remédios não são vergonha. Seu cérebro também merece cuidado.", 
  "Falar sobre sua dor é o primeiro passo para aliviá-la.", 
  "Você não está 'inventando' sofrimento. Sua dor é real e merece atenção.", 
  "Buscar ajuda é como colocar um colete salva-vidas: não resolve a tempestade, mas te ajuda a flutuar.", 
  "Você não é um incômodo. As pessoas querem te ver bem.", 
  "Ajuda profissional não é 'ultimo recurso', é autocuidado preventivo.", 
  "Você merece apoio, mesmo que não acredite nisso agora.", 
  "Respire. Você está aqui. Isso já é o suficiente.", 
  "Um dia de cada vez.", 
  "Isso também vai passar.", 
  "Você é mais forte do que pensa.", 
  "Permita-se sentir, mas não afundar.", 
  "Não desista de si mesmo(a).", 
  "A esperança existe, mesmo quando você não a vê.", 
  "Você não está sozinho(a).", 
  "Sua vida importa.", 
  "Amanhã é uma nova página.", 
  "A noite pode parecer infinita, mas o sol sempre nasce de novo.", 
  "Se não consegue dormir, descanse. Seu corpo agradece pelo repouso.", 
  "Os pensamentos noturnos são os mais mentirosos. Não acredite neles.", 
  "A escuridão não apaga sua luz interior.", 
  "Você já sobreviveu a todas as suas noites difíceis. Essa não será diferente.", 
  "Cicatrizes são provas de que você lutou e sobreviveu.", 
  "Você não está voltando para trás, está se preparando para um novo começo.", 
  "Crescer dói, mas ficar parado(a) na dor dói mais.", 
  "Sua história não termina aqui. Há sempre uma chance de recomeçar.", 
  "A cura começa quando você para de se punir por sentir.", 
  "Você não perdeu tempo: estava se reconstruindo em silêncio.", 
  "Não subestime o poder de pequenos progressos.", 
  "Até as árvores perdem folhas e renascem. Você também pode.", 
  "Seu passado não dita seu futuro. Você pode ressignificá-lo.", 
  "A força não é não cair, mas levantar todas as vezes que for preciso.", 
  "Você é mais do que os pensamentos negativos que sua mente cria.", 
  "Não espere ser ‘perfeito(a)’ para se amar. Comece agora, como você está.", 
  "Seu valor não depende da opinião alheia.", 
  "Você é único(a). Não há ninguém igual para trazer o que você oferece ao mundo.", 
  "Autocuidado não é egoísmo, é sobrevivência.", 
  "Você merece amor, especialmente o seu próprio.", 
  "Não se compare. Você está em uma jornada que só sua alma entende.", 
  "Sorrir não é obrigação. Suas emoções são válidas, mesmo as difíceis.", 
  "Você não é ‘demais’. Você é exatamente o que o mundo precisa.", 
  "Seja gentil com o seu ‘eu’ do passado. Ele(a) fez o melhor que pôde.", 
  "Não acredite em tudo que sua mente diz quando está triste.",
  "Pensamentos são passageiros. Eles não definem quem você é.",
  "Troque ‘eu não consigo’ por ‘eu vou tentar’.",
  "Você merece amor, especialmente o seu próprio.",
  "Não se compare. Você está em uma jornada que só sua alma entende.",
  "Sorrir não é obrigação. Suas emoções são válidas, mesmo as difíceis.",
  "Você não é ‘demais’. Você é exatamente o que o mundo precisa.",
  "Seja gentil com o seu ‘eu’ do passado. Ele(a) fez o melhor que pôde.",
  "Você já superou obstáculos antes. Este é só mais um.",
  "Não alimente o que te faz mal. Troque o foco para o que te fortalece.",
  "Sua mente não é sua inimiga. Ela só está cansada e precisa de cuidado.",
  "O ‘eu’ de amanhã agradecerá por você não ter desistido hoje.",
  "Pare de se sabotar. Você merece sua própria torcida.",
  "A dor é temporária, mas a força que você ganha com ela fica.",
  "Você não está preso(a) nesse pensamento. Deixe-o ir.",
  "Não subestime o poder de um único passo. Grandes jornadas começam assim.",
  "Se não consegue correr, ande. Se não consegue andar, rasteje. Mas não pare.",
  "Celebre as pequenas vitórias: levantar, tomar água, respirar fundo.",
  "Um minuto de cada vez. Você não precisa resolver tudo hoje.",
  "Progresso é progresso, não importa o tamanho.", 
]

function firstMsg(){
   frase = document.getElementById("frase")
   numero_aleatorio = Math.floor(Math.random() * 105);
   sorteio_frase = frases_motivadoras[numero_aleatorio];
   document.getElementById("frase").innerText = sorteio_frase;
}


document.addEventListener("DOMContentLoaded", firstMsg);



function newMsg(){
  frase = document.getElementById("frase")
  numero_aleatorio = Math.floor(Math.random() * 105);
  sorteio_frase = frases_motivadoras[numero_aleatorio];
  document.getElementById("frase").innerText = sorteio_frase;
}

